test_dir('tests')language: r

sudo: false

install:
  - R -e 'install.packages(c("Rcpp", "RcppArmadillo", "knitr", "ggplot2", "rmarkdown", "testthat"))'

script: 
  - Rscript -e "library(testthat);invisible(source_dir('./',env=globalenv()));test_dir('tests/testthat/');test_dir('tests/testthat/',reporter='stop')"

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

r_packages:
 - devtools
 - knitr

cache:
  packages: false
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

notifications:
  email: false
